[".config/yazi/theme.toml"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/yazi/refs/heads/main/themes/mocha/catppuccin-mocha-mauve.toml"
    refreshPeriod = "168h"

[".config/zellij/themes/catppuccin.kdl"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/zellij/refs/heads/main/catppuccin.kdl"
    refreshPeriod = "168h"
