# Catppuccin Themes
[".config/zellij/themes/catppuccin.kdl"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/zellij/refs/heads/main/catppuccin.kdl"
    refreshPeriod = "168h"

[".profile.d/fzf-theme.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/fzf/refs/heads/main/themes/catppuccin-fzf-mocha.sh"
    refreshPeriod = "168h"

[".config/btop/themes/catppuccin_mocha.theme"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/btop/refs/heads/main/themes/catppuccin_mocha.theme"
    refreshPeriod = "168h"

[".config/bat/themes/Catppuccin Mocha.tmTheme"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/bat/refs/heads/main/themes/Catppuccin%20Mocha.tmTheme"
    refreshPeriod = "168h"

[".config/git/catppuccin.gitconfig"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/delta/refs/heads/main/catppuccin.gitconfig"
    refreshPeriod = "168h"

[".config/atuin/themes/catppuccin-mocha-mauve.toml"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/atuin/refs/heads/main/themes/mocha/catppuccin-mocha-mauve.toml"
    refreshPeriod = "168h"

# Fonts
[".local/share/fonts/JetBrainsMono"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip"
    refreshPeriod = "744h"
    include = ["*.ttf"]
