#
##
### LSP settings
##
#

### typos
[language-server.typos]
command = "typos-lsp"

### sql-language-server
[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

### ltex-ls
[language-server.ltex-ls.config]
ltex.enabled = true
ltex.completionEnabled = true
ltex.statusBarItem = true
ltex.language = "ru-RU"
ltex.dictionary = { "ru-RU" = ["builtin"] }

### helix-snippets
[language-server.helix-snippets-ls]
command = "helix-snippets-ls"
args = ["--stdio"]

### python
[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
[language-server.ruff]
command = "ruff"
args = ["server"]

### php
[language-server.phpactor]
command = "phpactor"
args = ["language-server"]

#
##
### Languages settings
##
#

##### Language: MARKDOWN #####
[[language]]
name = "markdown"
language-servers = ["ltex-ls"]

##### Language: DOCKERFILE #####
[[language]]
name = "dockerfile"
language-servers = ["docker-langserver", "typos"]
indent = { tab-width = 4, unit = "    " }

##### Language: PHP #####
[[language]]
name = "php"
auto-format = true
language-servers = [ "phpactor", "typos", "helix-snippets-ls" ]
indent = { tab-width = 4, unit = "    " }

[language.auto-pairs]
"'" = "'"
'<' = '>'
'(' = ')'
'{' = '}'
'[' = ']'
'`' = '`'
'"' = '"'

[language.debugger]
name = "php"
transport = "stdio"
command = "node"
args = ["~/gits/vscode-php-debug/out/phpDebug.js"]

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [{ name = "entrypoint", completion = "filename" }]
args = { mode = "debug", program = "{0}" }

##### Language: SQL #####
[[language]]
name = "sql"
language-servers = ["sql-language-server", "typos"]

##### Language: JAVASCRIPT #####
[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "typos"]
indent = { tab-width = 4, unit = "    " }
auto-format = true
file-types = ["js"]
formatter = { command = 'prettier', args = [
  "--parser", "typescript",
  "--tab-width", "4",
  "--print-width", "100"
] }

##### Language: TYPESCRIPT #####
[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "typos"]
indent = { tab-width = 4, unit = "    " }
auto-format = true
file-types = ["js"]
formatter = { command = 'prettier', args = [
  "--parser", "typescript",
  "--tab-width", "4",
  "--print-width", "100"
] }

##### Language: JSON #####
[[language]]
name = "json"
file-types = ["jsonc", "json"]
indent = { tab-width = 4, unit = "    " }

##### Language: CSS #####
[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "typos"]
indent = { tab-width = 4, unit = "    " }

##### Language: SCSS #####
[[language]]
name = "scss"
language-servers = ["vscode-css-language-server", "typos"]
indent = { tab-width = 4, unit = "    " }

##### Language: HTML #####
[[language]]
name = "html"
indent = { tab-width = 4, unit = "    " }

##### Language: GIT-COMMIT #####
[[language]]
name = "git-commit"
language-servers = ["typos", "ltex-ls"]
##### Language: GIT-CONFIG #####
[[language]]
name = "git-config"
file-types = [
  "gitconfig",
  { glob = ".gitmodules" },
  { glob = ".gitconfig" },
  { glob = ".git/config" },
  { glob = ".config/git/config" },
  { glob = "git/config.tmpl" },
]

##### Language: PYTHON #####
[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
auto-format = true

##### Language: YAML #####
[[language]]
name = "yaml"
formatter = { command = "prettierd", args = [".yaml"] }
auto-format = true

##### Language: BASH #####
[[language]]
name = "bash"
auto-format = true
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
language-servers = ["bash-language-server", "typos"]
file-types = [
  "sh",
  "bash",
  { glob = "i3/config" },
  { glob = "sway/config" },
  { glob = ".bash_history" },
  { glob = ".bash_profile" },
  { glob = ".bashrc" },
  { glob = ".profile" },
  { glob = ".bash_aliases" },
  { glob = ".Renviron" },
  { glob = ".xprofile" },
  { glob = ".xsession" },
  { glob = ".xsessionrc" },
  { glob = "dot_bashrc" },
  { glob = "i3/**.tmpl" },
]

##### Language: TOML #####
[[language]]
name = "toml"
file-types = ["toml", { glob = "*.toml.tmpl" }]

##### Language: LUA #####
[[language]]
name = "lua"
file-types = ["lua", { glob = "*.lua.tmpl" }]
