# full update
full-update: sys-update full-usr-update

# full user-space update
full-usr-update: flat-update brew-update pnpm-update chezmoi-update


# update system
sys-update:
    sudo zypper ref && sudo zypper dup -y

# update flatpak
flat-update:
    flatpak update -y

# update pnpm
pnpm-update:
    pnpm -g update

# update qtile
qtile-update:
    uv tool install qtile

# update brew
brew-update:
    brew update && brew upgrade -y

# update chezmoi
chezmoi-update:
    chezmoi update --apply --init


# distrobox assemble
d_box-init:
    distrobox assemble create --file ~/.config/distroboxses.ini


