# full update
full-update: sys-update full-usr-update

# full user-space update
full-usr-update: flat-update brew-update pnpm-update


# update system
sys-update:
    sudo zypper ref && sudo zypper dup -y

# update flatpak
flat-update:
    flatpak update -y

# update pnpm
pnpm-update:
    pnpm -g update

# update brew
brew-update:
    brew update && brew upgrade
